id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 1
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 10
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addReply:
          reply: This issue has been automatically marked as stale because it has marked as requiring author feedback but has not had any activity for **10 days**. It will be closed if no further activity occurs **within 10 days of this comment**. Thank you for your contributions to OneDrive API Docs!
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: status:answered
      - noActivitySince:
          days: 10
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has marked as answered but has not had any activity for **10 days**. It will be closed if no further activity occurs **within 10 days of this comment**. Thank you for your contributions to OneDrive API Docs!
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: status:resolved
      - noActivitySince:
          days: 10
      - isNotLabeledWith:
          label: no-recent-activity
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has marked as resolved but has not had any activity for **10 days**. It will be closed if no further activity occurs **within 10 days of this comment**. Thank you for your contributions to OneDrive API Docs!
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: no-recent-activity
      - noActivitySince:
          days: 10
      actions:
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - not:
          isActivitySender:
            user: microsoft-github-bot
            issueAuthor: False
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: no-recent-activity
      then:
      - removeLabel:
          label: no-recent-activity
      description: 
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isActivitySender:
            user: microsoft-github-bot
            issueAuthor: False
      - isOpen
      - isAction:
          action: Labeled
      - labelAdded:
          label: ask-to:azure-active-directory
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      - addReply:
          reply: 'Thanks for your feedback. Since this question is about Azure Active Directory, could you please ask it here: https://stackoverflow.com/questions/tagged/azure-active-directory<br>Thanks!'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isActivitySender:
            user: microsoft-github-bot
            issueAuthor: False
      - isOpen
      - isAction:
          action: Labeled
      - labelAdded:
          label: 'Needs: More Information'
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      - addReply:
          reply: Thanks for your feedback; however, we need more information to understand the issue further.  If you have not provided the following information, could you please provide the following?<br><br>Could you please provide the following response headers:<br> - Date (in UTC, please)<br> - request-id<br> - SPRequestGuid (for requests made to OneDrive for Business and SharePoint)<br>Please provide as recent values as possible.<br><br>Could you please describe the steps to reproduce the bug in sufficient detail for another person to be able to reproduce it?<br><br>Could you please provide sample requests and responses that illustrate the issue that you are encountering?<br><br>Could you please describe the behavior you expected to occur when performing the action?
      - removeLabel:
          label: 'Needs: More Information'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isActivitySender:
            user: microsoft-github-bot
            issueAuthor: False
      - isOpen
      - isLabeled
      - labelAdded:
          label: ask-to:graph
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      - addReply:
          reply: 'Thanks for your feedback. Since this question is about Microsoft Graph, could you please ask via the Microsoft Graph support site here: https://developer.microsoft.com/en-us/graph/support<br>Thanks!'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isActivitySender:
            user: microsoft-github-bot
            issueAuthor: False
      - isOpen
      - isLabeled
      - labelAdded:
          label: 'Needs: Support Case'
      then:
      - addReply:
          reply: Thanks for contacting us. This appears to require more investigation. If you have a support contact, could you please work through them to file a support case for us to do further investigation on this issue?
      - removeLabel:
          label: 'Needs: Support Case'
      - addLabel:
          label: 'Needs: Author Feedback'
      description: 
onFailure: 
onSuccess: 
